"""Regional random-encounter system with stalking behavior.

Drives wilderness encounters in the seven outdoor regions (Kinsweave,
Eternal Steppe, Infinite Desert, Gatefall, Deepwater, Tidebloom, Twin
Rivers).  Encounter rolls fire at four fixed game-hours per day -- two
during the day, two at night, with a higher base chance at night.  When
a roll triggers, a creature drawn from that region's CR-bucketed table
spawns two rooms away from a target player and stalks them through the
room graph.

Encounters never fire in cities, towns, or indoor rooms; the eligibility
filter checks for any of the urban/safe-zone flags listed in
``EXCLUDED_FLAGS``.

Tables are generated by ``scripts/build_encounter_tables.py`` and live
in ``data/encounter_tables/``.  This module loads them at startup.
"""

from __future__ import annotations

import json
import logging
import os
import random
import time
from collections import deque
from typing import Dict, List, Optional, Set, Tuple, Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Room flags that mark a room as ineligible for encounters.  Any room
# carrying one of these is treated as a city/town/indoor space.
EXCLUDED_FLAGS: Set[str] = {
    "safe", "indoor", "shop", "temple", "market", "street", "inn",
    "tavern", "guild", "gate", "dock", "residential", "forge",
    "academy", "altar",
}

# Fixed game-hours when encounter rolls fire.  Two daytime slots and two
# nighttime slots per game day.
DAY_ROLL_HOURS:   Tuple[int, ...] = (9, 15)
NIGHT_ROLL_HOURS: Tuple[int, ...] = (22, 3)

# Per-roll, per-region chance to spawn an encounter.
DAY_ROLL_CHANCE   = 0.40
NIGHT_ROLL_CHANCE = 0.65

# Standard D&D 3.5 APL band.  A creature is eligible if its CR is within
# +/- 2 of the party APL (clamped to [APL-2, APL+2]).
CR_BAND_BELOW = 2
CR_BAND_ABOVE = 2

# Stalker behavior tuning
STALKER_SPAWN_DISTANCE = 2          # rooms away from target on spawn
STALKER_MAX_LIFETIME_SECS = 600     # despawn after 10 min if not engaged
STALKER_VNUM_BASE = 900000          # well above any authored mob vnum

# Where stalker mobs come from (avoid colliding with mobs.json's vnums).
_next_stalker_vnum = STALKER_VNUM_BASE


def _allocate_stalker_vnum() -> int:
    global _next_stalker_vnum
    v = _next_stalker_vnum
    _next_stalker_vnum += 1
    return v


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def _data_dir() -> str:
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", "data"))


def _tables_dir() -> str:
    return os.path.join(_data_dir(), "encounter_tables")


def load_region_map() -> Dict[str, Set[int]]:
    """Return ``{region: {vnum, ...}}`` mapping for fast room lookup."""
    path = os.path.join(_tables_dir(), "region_map.json")
    if not os.path.exists(path):
        logger.warning("encounters: region_map.json missing at %s", path)
        return {}
    with open(path, "r", encoding="utf-8") as f:
        raw = json.load(f)
    return {region: set(vnums) for region, vnums in raw.items()}


def load_encounter_tables() -> Dict[str, Dict[str, list]]:
    """Return ``{region: {cr_bucket: [creature, ...]}}``.

    Missing region files are skipped with a warning rather than raising.
    """
    out: Dict[str, Dict[str, list]] = {}
    tdir = _tables_dir()
    if not os.path.isdir(tdir):
        logger.warning("encounters: tables dir missing at %s", tdir)
        return out
    for fn in os.listdir(tdir):
        if fn == "region_map.json" or not fn.endswith(".json"):
            continue
        region = fn[:-5]
        try:
            with open(os.path.join(tdir, fn), "r", encoding="utf-8") as f:
                payload = json.load(f)
            buckets = payload.get("buckets", {})
            if isinstance(buckets, dict):
                out[region] = buckets
        except (OSError, json.JSONDecodeError) as e:
            logger.warning("encounters: failed to load %s: %s", fn, e)
    return out


# ---------------------------------------------------------------------------
# Eligibility helpers
# ---------------------------------------------------------------------------

def is_eligible_room(room) -> bool:
    """True if `room` is a valid encounter location (wilderness, outdoors)."""
    if room is None:
        return False
    flags = {str(f).lower() for f in (getattr(room, "flags", []) or [])}
    return not (flags & EXCLUDED_FLAGS)


def region_for_room(room, region_map: Dict[str, Set[int]]) -> Optional[str]:
    """Return the region key containing this room, or None."""
    if room is None:
        return None
    vnum = getattr(room, "vnum", None)
    if vnum is None:
        return None
    for region, vnums in region_map.items():
        if vnum in vnums:
            return region
    return None


# ---------------------------------------------------------------------------
# Pathfinding (BFS through Room.exits)
# ---------------------------------------------------------------------------

def bfs_path(world, start_vnum: int, goal_vnum: int,
             max_depth: int = 12) -> Optional[List[int]]:
    """Return list of room vnums from start to goal (inclusive), or None."""
    if start_vnum == goal_vnum:
        return [start_vnum]
    visited: Set[int] = {start_vnum}
    queue: deque = deque([(start_vnum, [start_vnum])])
    while queue:
        cur, path = queue.popleft()
        if len(path) > max_depth:
            continue
        room = world.rooms.get(cur)
        if room is None:
            continue
        for direction, next_vnum in (room.exits or {}).items():
            if not isinstance(next_vnum, int):
                continue
            if next_vnum in visited:
                continue
            new_path = path + [next_vnum]
            if next_vnum == goal_vnum:
                return new_path
            visited.add(next_vnum)
            queue.append((next_vnum, new_path))
    return None


def find_spawn_room(world, target_vnum: int, region_vnums: Set[int],
                    distance: int = STALKER_SPAWN_DISTANCE,
                    max_attempts: int = 24) -> Optional[int]:
    """BFS outward from the target to find an eligible room exactly `distance`
    rooms away.  Falls back to distance-1 or distance+1 if needed.
    """
    visited: Set[int] = {target_vnum}
    queue: deque = deque([(target_vnum, 0)])
    candidates_at: Dict[int, List[int]] = {distance: [],
                                           distance - 1: [],
                                           distance + 1: []}
    attempts = 0
    while queue and attempts < max_attempts * 4:
        cur, depth = queue.popleft()
        attempts += 1
        if depth > distance + 1:
            continue
        room = world.rooms.get(cur)
        if room is None:
            continue
        if depth in candidates_at and cur != target_vnum:
            if cur in region_vnums and is_eligible_room(room):
                candidates_at[depth].append(cur)
        for next_vnum in (room.exits or {}).values():
            if not isinstance(next_vnum, int) or next_vnum in visited:
                continue
            visited.add(next_vnum)
            queue.append((next_vnum, depth + 1))

    for d in (distance, distance - 1, distance + 1):
        if candidates_at.get(d):
            return random.choice(candidates_at[d])
    return None


# ---------------------------------------------------------------------------
# Mob spawn
# ---------------------------------------------------------------------------

def _instantiate_mob(template: dict, room_vnum: int):
    """Build a live ``Mob`` instance from a bestiary template dict."""
    from src.mob import Mob

    vnum = _allocate_stalker_vnum()
    name = template.get("name") or "stalking creature"
    level = int(template.get("level") or max(1, int(template.get("cr", 1))))
    hp_dice = tuple(template.get("hp_dice") or (level, 8, 0))
    ac = int(template.get("ac") or (10 + max(0, int(template.get("cr", 1)))))
    damage_dice = tuple(template.get("damage_dice") or (1, 6, 0))

    mob = Mob(
        vnum=vnum,
        name=name,
        level=level,
        hp_dice=hp_dice,
        ac=ac,
        damage_dice=damage_dice,
        flags=list(template.get("flags") or []) + ["encounter", "hostile"],
        type_=template.get("type_") or "humanoid",
        alignment=template.get("alignment") or "neutral",
        environment=template.get("environment") or "",
        organization=template.get("organization") or "solitary",
        cr=template.get("cr"),
        description=template.get("description") or "",
    )
    mob.room_vnum = room_vnum
    mob.alive = True

    # Optional fields the constructor may not accept directly
    for opt in ("ability_scores", "speed", "attacks", "special_attacks",
                "special_qualities", "feats", "skills", "saves"):
        val = template.get(opt)
        if val is not None and not getattr(mob, opt, None):
            try:
                setattr(mob, opt, val)
            except Exception:
                pass

    return mob


# ---------------------------------------------------------------------------
# Stalker
# ---------------------------------------------------------------------------

class Stalker:
    """A spawned encounter mob actively hunting a target player or party."""

    __slots__ = ("mob", "region", "target", "party", "spawned_at",
                 "last_target_vnum", "warnings_sent", "engaged", "given_up")

    def __init__(self, mob, region: str, target, party: List):
        self.mob = mob
        self.region = region
        self.target = target          # primary target Character
        self.party = list(party)      # may be [target] for solo
        self.spawned_at = time.time()
        self.last_target_vnum = getattr(target.room, "vnum", None) \
            if getattr(target, "room", None) else None
        self.warnings_sent = 0
        self.engaged = False
        self.given_up = False

    def is_solo(self) -> bool:
        return len(self.party) <= 1

    def expired(self) -> bool:
        return (time.time() - self.spawned_at) > STALKER_MAX_LIFETIME_SECS


# ---------------------------------------------------------------------------
# Encounter manager
# ---------------------------------------------------------------------------

class EncounterManager:
    """Schedules region encounter rolls and ticks active stalkers."""

    def __init__(self):
        self.region_map: Dict[str, Set[int]] = {}
        self.tables: Dict[str, Dict[str, list]] = {}
        self.active: List[Stalker] = []
        # Per-(region, hour) -> game-day index of last fired roll
        self.last_roll: Dict[Tuple[str, int], int] = {}
        self.enabled = True
        self._loaded = False

    # -- lifecycle ---------------------------------------------------------

    def load(self) -> None:
        self.region_map = load_region_map()
        self.tables = load_encounter_tables()
        self._loaded = True
        n_creatures = sum(sum(len(b) for b in t.values())
                          for t in self.tables.values())
        logger.info("encounters: loaded %d regions, %d creatures",
                    len(self.tables), n_creatures)

    # -- region / party helpers -------------------------------------------

    def players_in_region(self, world, region: str) -> List:
        vnums = self.region_map.get(region, set())
        out = []
        for p in getattr(world, "players", []) or []:
            if getattr(p, "is_ai", False):
                continue
            room = getattr(p, "room", None)
            if room is None:
                continue
            if getattr(room, "vnum", None) in vnums and is_eligible_room(room):
                out.append(p)
        return out

    def _party_apl(self, party: List) -> int:
        if not party:
            return 1
        levels = [max(1, int(getattr(p, "level", 1))) for p in party]
        # 3.5 APL = average party level, rounded; for solo just use level.
        return max(1, round(sum(levels) / len(levels)))

    # -- table selection --------------------------------------------------

    def pick_creature(self, region: str, apl: int) -> Optional[dict]:
        buckets = self.tables.get(region, {})
        if not buckets:
            return None
        candidates: List[dict] = []
        for cr_low in range(max(0, apl - CR_BAND_BELOW), apl + CR_BAND_ABOVE + 1):
            candidates.extend(buckets.get(str(cr_low), []))
        # Always allow the lowest bucket for low-level parties so APL 1-2
        # don't see empty tables.
        if not candidates and apl <= 2:
            candidates = list(buckets.get("0", [])) + list(buckets.get("1", []))
        if not candidates:
            return None
        return random.choice(candidates)

    # -- roll & spawn -----------------------------------------------------

    def maybe_roll(self, world, game_time) -> List[str]:
        """Check the schedule; for any due (region, hour) slot fire a roll."""
        if not self.enabled or not self._loaded:
            return []

        messages: List[str] = []
        is_night = bool(getattr(game_time, "is_nighttime", lambda: False)())
        hour = int(getattr(game_time, "hour", 0))
        # Use day-of-year-ish counter to avoid double-firing.  We don't
        # have a real calendar, so derive a synthetic "day number" from
        # wall clock so each in-game day fires its 4 rolls once.
        day_id = int(time.time() // 86400)

        slot_hours = NIGHT_ROLL_HOURS if is_night else DAY_ROLL_HOURS
        if hour not in slot_hours:
            return []

        chance = NIGHT_ROLL_CHANCE if is_night else DAY_ROLL_CHANCE

        for region in self.tables:
            key = (region, hour)
            if self.last_roll.get(key) == day_id:
                continue
            self.last_roll[key] = day_id

            party = self.players_in_region(world, region)
            if not party:
                continue

            # Scale roll by the lead player's rep in this region --
            # negative rep makes encounters more frequent.
            lead = party[0]
            try:
                from src.patronage import check_encounter_chance_multiplier
                mult = check_encounter_chance_multiplier(lead, region)
            except Exception:
                mult = 1.0
            if random.random() > chance * mult:
                continue

            spawned = self._spawn_for_party(world, region, party)
            if spawned:
                messages.append(spawned)

        return messages

    def _spawn_for_party(self, world, region: str, party: List) -> Optional[str]:
        # Pick the target -- if multiple players, pick one in the most
        # populous room (the "lead" room).
        room_counts: Dict[int, List] = {}
        for p in party:
            v = p.room.vnum
            room_counts.setdefault(v, []).append(p)
        target_vnum, group = max(room_counts.items(), key=lambda x: len(x[1]))
        target = group[0]

        # Patron-intervention check: friendly factions in this region may
        # cancel or soften the encounter based on the target's reputation.
        try:
            from src.patronage import check_intervention, on_intervention_used
            intervention = check_intervention(target, region)
        except Exception:
            intervention = None
        if intervention is not None and intervention.cancels_encounter:
            # Cancel the encounter entirely and narrate the intervention
            self._notify_party(group, intervention.player_message)
            try:
                on_intervention_used(target, intervention)
            except Exception:
                pass
            return (f"[Encounter] patron intervention ({intervention.type}, "
                    f"{intervention.faction_id}) saved {target.name} in {region}")

        apl = self._party_apl(group)
        creature = self.pick_creature(region, apl)
        if creature is None:
            logger.debug("encounters: no candidate for %s @ APL %d",
                         region, apl)
            return None

        spawn_vnum = find_spawn_room(world, target_vnum,
                                     self.region_map.get(region, set()))
        if spawn_vnum is None:
            logger.debug("encounters: no spawn room near %d in %s",
                         target_vnum, region)
            return None

        spawn_room = world.rooms.get(spawn_vnum)
        if spawn_room is None:
            return None

        mob = _instantiate_mob(creature, spawn_vnum)
        world.mobs[mob.vnum] = mob
        spawn_room.mobs.append(mob)

        stalker = Stalker(mob, region, target, group)
        self.active.append(stalker)
        self._notify_party(group,
            f"\033[1;31mYou feel something hunting you from nearby. "
            f"({mob.name} stirs in the {region.replace('_',' ')}.)\033[0m")
        stalker.warnings_sent = 1

        # Witness intervention (cancels_encounter=False): the encounter
        # fires but the player gets advance warning.
        if intervention is not None and not intervention.cancels_encounter:
            self._notify_party(group, intervention.player_message)
            try:
                from src.patronage import on_intervention_used
                on_intervention_used(target, intervention)
            except Exception:
                pass

        # 10% chance the encounter is carrying a captive -- a freshly
        # abducted Kin being dragged off to the captors' lair.  Spawns
        # the captive in the same room as the stalker so clearing the
        # stalker frees the captive.
        captive_note = ""
        if random.random() < 0.10:
            try:
                captive_note = self._maybe_attach_captive(world, region,
                                                          spawn_vnum)
            except Exception as e:
                logger.debug("encounters: captive attach failed: %s", e)

        base_msg = (f"[Encounter] {mob.name} (CR {creature.get('cr')}) "
                    f"stalking {target.name} in {region} from room {spawn_vnum}")
        return base_msg + (captive_note if captive_note else "")

    def _maybe_attach_captive(self, world, region: str, room_vnum: int) -> str:
        """Spawn a bound captive in the stalker's room.  Picks a family
        whose region matches the encounter region when possible, else a
        random family.  Rolls a weighted rescue_type so some encounters
        carry leaders, some plant-captives, etc."""
        from src.captives import (get_data, spawn_captive_in_room,
                                  _roll_rescue_type)
        d = get_data()
        regional = d.get_family_for_region(region)
        if regional:
            family = random.choice(regional)
        elif d.families:
            family = random.choice(list(d.families.values()))
        else:
            return ""

        template_options = list(d.templates.keys()) or ["scout"]
        template = random.choice(template_options)
        rescue_type = _roll_rescue_type()

        ok, msg = spawn_captive_in_room(
            world, room_vnum,
            template_id=template,
            family_id=family["id"],
            captor_type=f"{region} encounter group",
            rescue_type=rescue_type,
        )
        if not ok:
            return ""
        return f" | captive attached: family={family['id']}, type={rescue_type}"

    # -- stalker tick -----------------------------------------------------

    def tick_stalkers(self, world) -> List[str]:
        """Advance each active stalker; report status changes."""
        messages: List[str] = []
        survivors: List[Stalker] = []

        for s in self.active:
            if s.engaged or s.given_up:
                continue
            try:
                msg = self._advance(world, s)
                if msg:
                    messages.append(msg)
                if s.expired() and not s.engaged:
                    self._despawn(world, s, gave_up=True)
                    messages.append(
                        f"[Encounter] {s.mob.name} loses the trail and "
                        f"melts back into the {s.region}."
                    )
                    s.given_up = True
                else:
                    survivors.append(s)
            except Exception as e:
                logger.exception("encounters: stalker tick error: %s", e)

        self.active = survivors
        return messages

    def _advance(self, world, s: Stalker) -> Optional[str]:
        target_room = getattr(s.target, "room", None)
        if target_room is None:
            return None
        target_vnum = target_room.vnum

        # Already in the target's room -> engage immediately.
        if s.mob.room_vnum == target_vnum:
            return self._engage(world, s, target_room)

        # If party is moving and we have multiple players, hold ground.
        # Solo player gets pursued regardless.
        moved = (s.last_target_vnum is not None
                 and s.last_target_vnum != target_vnum)
        s.last_target_vnum = target_vnum
        if moved and not s.is_solo():
            return None

        # Pathfind toward the target
        path = bfs_path(world, s.mob.room_vnum, target_vnum)
        if not path or len(path) < 2:
            return None
        next_vnum = path[1]
        next_room = world.rooms.get(next_vnum)
        if next_room is None:
            return None

        # Move the mob
        old_room = world.rooms.get(s.mob.room_vnum)
        if old_room and s.mob in old_room.mobs:
            old_room.mobs.remove(s.mob)
        next_room.mobs.append(s.mob)
        s.mob.room_vnum = next_vnum

        # Arrived in target's room this tick -> engage now, no half-round gap.
        if next_vnum == target_vnum:
            return self._engage(world, s, target_room)

        # Escalating warnings to the party
        rooms_remaining = len(path) - 2  # rooms between mob and target
        if rooms_remaining == 1 and s.warnings_sent < 2:
            self._notify_party(s.party,
                f"\033[1;33mYou hear movement very close -- something is "
                f"almost upon you.\033[0m")
            s.warnings_sent = 2
        return None

    def _engage(self, world, s: Stalker, target_room) -> str:
        """Mark the stalker engaged and hand off to the combat system."""
        s.engaged = True
        from src.chat import broadcast_to_room
        broadcast_to_room(
            target_room,
            f"\033[1;31m{s.mob.name} bursts into the area, eyes locked "
            f"on {s.target.name}!\033[0m",
        )
        # Initiate combat: primary target first, then drag any other
        # party members in the same room into the fight.
        try:
            from src.combat import start_combat
            combat = start_combat(target_room, s.mob, s.target)
            for member in s.party:
                if member is s.target:
                    continue
                if getattr(member, "room", None) is target_room:
                    combat.add_combatant(member)
        except Exception as e:
            logger.exception(
                "encounters: failed to start combat for %s vs %s: %s",
                s.mob.name, s.target.name, e
            )
        return f"[Encounter] {s.mob.name} engaged {s.target.name}"

    def _notify_party(self, party: List, message: str) -> None:
        from src.chat import send_to_player
        for p in party:
            send_to_player(p, message)

    def _despawn(self, world, s: Stalker, gave_up: bool) -> None:
        room = world.rooms.get(s.mob.room_vnum)
        if room and s.mob in room.mobs:
            room.mobs.remove(s.mob)
        world.mobs.pop(s.mob.vnum, None)
        if gave_up:
            self._notify_party(s.party,
                f"\033[2;37mThe sense of being watched fades.\033[0m")

    # -- combined tick (called by main loop) ------------------------------

    def tick(self, world, game_time) -> List[str]:
        out: List[str] = []
        out.extend(self.maybe_roll(world, game_time))
        out.extend(self.tick_stalkers(world))
        return out

    # -- admin helpers ----------------------------------------------------

    def force_encounter(self, world, region: str,
                        target_player) -> Tuple[bool, str]:
        """Admin: immediately spawn a stalker against ``target_player``."""
        if region not in self.tables:
            return False, f"Unknown region '{region}'."
        room = getattr(target_player, "room", None)
        if room is None or not is_eligible_room(room):
            return False, "Target is not in an encounter-eligible room."
        if room.vnum not in self.region_map.get(region, set()):
            return False, f"Target is not currently in {region}."
        msg = self._spawn_for_party(world, region, [target_player])
        return (msg is not None, msg or "Failed to spawn encounter.")

    def status(self) -> str:
        lines = [
            f"Encounters enabled: {self.enabled}",
            f"Active stalkers: {len(self.active)}",
            f"Regions loaded: {', '.join(sorted(self.tables))}",
        ]
        for s in self.active:
            lines.append(f"  - {s.mob.name} (CR {s.mob.cr}) hunting "
                         f"{s.target.name} in {s.region} "
                         f"[engaged={s.engaged}]")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Singleton accessor
# ---------------------------------------------------------------------------

_encounter_mgr: Optional[EncounterManager] = None


def get_encounter_manager() -> EncounterManager:
    global _encounter_mgr
    if _encounter_mgr is None:
        _encounter_mgr = EncounterManager()
        _encounter_mgr.load()
    return _encounter_mgr
